apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-demo-app
  namespace: monitoring-app
  labels:
    app: monitoring-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitoring-demo-app
  template:
    metadata:
      labels:
        app: monitoring-demo-app
    spec:
      containers:
        - name: monitoring-demo-app
          image: monitoring-demo-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80