apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-demo-servicemonitor
  namespace: monitoring
  labels:
    release: my-prom-stack
spec:
  namespaceSelector:
    matchNames:
      - monitoring-app

  selector:
    matchLabels:
      app: monitoring-demo-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s